### PR TITLE
Add Python 3.8, update to latest Python and Tox versions

### LINKED ISSUE #8: pypy is pypy3.3
I've been playing with docker-tox on Circle CI and I've run into the problem that currently `pypy` is pypy 3.3:

```shell
root@d3b024b08537:/app# pypy
Python 3.3.5 (ea9979b550eeae87924dc4bef06070e8f8d0e22f, Oct 13 2016, 11:32:23)
[PyPy 5.5.0-alpha0 with GCC 6.2.0] on linux
...
root@d3b024b08537:/app# pypy3
Python 3.5.3 (fdd60ed87e94, Apr 24 2018, 06:10:04)
[PyPy 6.0.0 with GCC 6.2.0 20160901] on linux
```

That's most likely caused by https://github.com/themattrix/docker-tox-base/commit/6a1549545e6091af897e44973023ab314a14d423

I guess kill off the penultimate line?

And maybe update the other versions while at it (notably 3.7.2)? 😇

### PR DESCRIPTION
**Pull request by bittner**
- Updates all Python versions to their latest version available from pyenv (~ Python.org)
- Adds Python 3.8.0 (released this Monday)
- Updates Tox to its latest stable version

Fixes #8.

### CODE REVIEW

**Comment by bittner** [comment]
@themattrix Would you mind merging?

**Comment by bittner** [comment]
Thanks for merging! :1st_place_medal: 

BTW, I'm not sure if we still need `pypy3.3-5.5-alpha`. I just left it in there, because I didn't want to try and break stuff.

**Comment by bittner** [comment]
Builds [on Docker Hub](https://hub.docker.com/r/themattrix/tox-base/tags) don't seem to be triggered automatically.

@themattrix Can you take a look?

Side note: I have an image that depends on `themattrix/tox`; only when that updates it also gets updated with the latest Pythons. :snake:

**Comment by themattrix** [comment]
*Should* be updated now - let me know if it's not!

**Comment by bittner** [comment]
That worked out, perfect! Autobuilds were triggered successfully. Thank you!

```
$ docker pull painless/tox
...
$ docker run --rm -it painless/tox sh
# bash
root@f82a1121d302:/app# for VERSION in 2.6 2.7 3.3 3.4 3.5 3.6 3.7 3.8; do python$VERSION --version; done
Python 2.6.9
Python 2.7.17
Python 3.3.7
Python 3.4.10
Python 3.5.7
Python 3.6.9
Python 3.7.5
Python 3.8.0
root@f82a1121d302:/app# pypy --version
Python 2.7.13 (4a68d8d3d2fc, Oct 10 2019, 06:43:13)
[PyPy 7.2.0 with GCC 6.2.0 20160901]
root@f82a1121d302:/app# pypy3 --version
Python 3.6.9 (5da45ced70e5, Oct 09 2019, 19:12:54)
[PyPy 7.2.0 with GCC 6.2.0 20160901]
```

**Pull request merged**
